sudo: required

services:
  - docker

script:
  - travis-build.sh

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push uvms/wildfly-full:$TIME;
    docker push uvms/wildfly-full;