sudo: required

services:
  - docker

env:
  - TIME=time

script:
  - docker build -t uvms/wildfly-full:$TIME --no-cache wildfly

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push uvms/wildfly-full:$TIME;
    docker push uvms/wildfly-full;