sudo: required

services:
  - docker

script:
  - docker build -t uvms/wildfly-full:$TRAVIS_JOB_NUMBER --no-cache wildfly

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push uvms/wildfly-full:$TRAVIS_JOB_NUMBER;
    docker push uvms/wildfly-full;